".\tools\lc\recomp.exe" "./gfx/en_new/lz_teamname_map.bin" "./gfx/en_new/lz/lz_teamname_map.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/en_new/lz_subtitle_gfx.bin" "./gfx/en_new/lz/lz_subtitle_gfx.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/en_new/lz_nintendo_gfx.bin" "./gfx/en_new/lz/lz_nintendo_gfx.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/en_new/D9.bin" "./gfx/en_new/lz/D9.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/en_new/tmp/39.bin" "./gfx/en_new/lz/39.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/en_new/tmp/3A.bin" "./gfx/en_new/lz/3A.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/en_new/tmp/3B.bin" "./gfx/en_new/lz/3B.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/en_new/img/intro.map" "./gfx/en_new/lz/3C.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/en_new/tmp/3D.bin" "./gfx/en_new/lz/3D.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/en_new/tmp/3E.bin" "./gfx/en_new/lz/3E.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/en_new/tmp/3F.bin" "./gfx/en_new/lz/3F.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/en_new/tmp/48.bin" "./gfx/en_new/lz/48.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/en_new/tmp/4A.bin" "./gfx/en_new/lz/4A.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/en_new/tmp/4B.bin" "./gfx/en_new/lz/4B.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/en_new/tmp/4D.bin" "./gfx/en_new/lz/4D.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/en_new/tmp/4E.bin" "./gfx/en_new/lz/4E.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/en_new/tmp/50.bin" "./gfx/en_new/lz/50.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/en_new/tmp/53.bin" "./gfx/en_new/lz/53.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/en_new/tmp/56.bin" "./gfx/en_new/lz/56.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/en_new/tmp/5A.bin" "./gfx/en_new/lz/5A.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/en_new/tmp/5E.bin" "./gfx/en_new/lz/5E.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/en_new/tmp/5F.bin" "./gfx/en_new/lz/5F.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/en_new/tmp/60.bin" "./gfx/en_new/lz/60.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/en_new/tmp/62.bin" "./gfx/en_new/lz/62.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/en_new/tmp/63.bin" "./gfx/en_new/lz/63.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/en_new/tmp/64.bin" "./gfx/en_new/lz/64.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/en_new/tmp/69.bin" "./gfx/en_new/lz/69.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/en_new/tmp/E0.bin" "./gfx/en_new/lz/E0.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/en_new/tmp/F8.bin" "./gfx/en_new/lz/F8.bin.lz" 0 19 0
