".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/00.bin" 0A5600h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/01.bin" 0CC6E0h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/02.bin" 0CE171h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/03.bin" 0CFBC0h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/04.bin" 0D17F8h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/05.bin" 0D33B7h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/06.bin" 0D4DC9h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/07.bin" 0D6764h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/08.bin" 0D7DADh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/09.bin" 0D97D4h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/0A.bin" 0DB386h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/0B.bin" 0DE356h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/0C.bin" 0E1B9Ah 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/0D.bin" 0E1C2Ah 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/0E.bin" 0E1CA5h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/0F.bin" 0E1D23h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/10.bin" 0E1DA1h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/11.bin" 0E1E1Fh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/12.bin" 0E1E97h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/13.bin" 0E1F13h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/14.bin" 0E1F90h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/15.bin" 0E2010h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/16.bin" 0E2090h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/17.bin" 0E2712h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/18.bin" 0E286Bh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/19.bin" 0E2E23h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/1A.bin" 0E4667h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/1B.bin" 0E6C94h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/1C.bin" 0E8E11h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/1D.bin" 0EBF3Ch 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/1E.bin" 0ED4E0h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/1F.bin" 0EFD4Bh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/20.bin" 0F15ACh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/21.bin" 0F4465h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/22.bin" 0F5E11h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/23.bin" 0F7583h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/24.bin" 0FA479h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/25.bin" 0FB04Eh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/26.bin" 0FC19Dh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/27.bin" 10584Eh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/28.bin" 1067CAh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/29.bin" 1098F9h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/2A.bin" 10CDD5h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/2B.bin" 11016Fh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/2C.bin" 112E3Dh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/2D.bin" 115780h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/2E.bin" 1166D5h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/2F.bin" 11A0D7h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/30.bin" 11B8B1h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/31.bin" 11CFDEh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/32.bin" 11D822h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/33.bin" 11E0E7h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/34.bin" 11FB8Ch 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/35.bin" 121964h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/36.bin" 122F5Eh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/37.bin" 1236B8h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/38.bin" 123726h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/39.bin" 123951h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/3A.bin" 1246DEh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/3B.bin" 12550Eh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/3C.bin" 1257F6h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/3D.bin" 125ADDh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/3E.bin" 125BB6h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/3F.bin" 12735Ch 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/40.bin" 1276AEh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/41.bin" 127F1Bh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/42.bin" 128890h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/43.bin" 128EF0h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/44.bin" 1297A8h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/45.bin" 129A23h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/46.bin" 129DECh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/47.bin" 12A7C3h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/48.bin" 12A9D0h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/49.bin" 12B55Dh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/4A.bin" 12BDA4h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/4B.bin" 12C7C8h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/4C.bin" 12D41Eh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/4D.bin" 12DEB0h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/4E.bin" 12E9BAh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/4F.bin" 12F278h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/50.bin" 12FBDAh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/51.bin" 130320h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/52.bin" 13180Dh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/53.bin" 132FC4h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/54.bin" 134CA1h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/55.bin" 135932h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/56.bin" 136BFEh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/57.bin" 1384BFh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/58.bin" 139A26h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/59.bin" 13B07Dh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/5A.bin" 13C578h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/5B.bin" 13DF2Fh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/5C.bin" 13F825h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/5D.bin" 1416B6h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/5E.bin" 142CE4h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/5F.bin" 1447AEh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/60.bin" 145F3Bh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/61.bin" 1476D5h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/62.bin" 1490F9h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/63.bin" 14A478h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/64.bin" 14B628h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/65.bin" 14CEBFh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/66.bin" 14DD65h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/67.bin" 14EF06h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/68.bin" 1501EAh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/69.bin" 151D31h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/6A.bin" 153005h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/6B.bin" 1537BFh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/6C.bin" 1537C4h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/6D.bin" 1537C9h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/6E.bin" 154FF5h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/6F.bin" 1568AEh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/70.bin" 157FFCh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/71.bin" 159A86h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/72.bin" 15A9BEh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/73.bin" 15BEDEh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/74.bin" 15D258h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/75.bin" 15DA25h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/76.bin" 15F449h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/77.bin" 160D60h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/78.bin" 1627A3h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/79.bin" 1641C3h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/7A.bin" 165B2Ah 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/7B.bin" 16754Bh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/7C.bin" 167698h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/7D.bin" 16769Dh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/7E.bin" 168FE1h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/7F.bin" 16AA84h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/80.bin" 16C6D1h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/81.bin" 16D8AFh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/82.bin" 16F0F7h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/83.bin" 170AFAh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/84.bin" 171F4Dh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/85.bin" 1736B8h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/86.bin" 175102h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/87.bin" 176606h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/88.bin" 17660Bh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/89.bin" 176610h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/8A.bin" 17794Bh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/8B.bin" 17910Fh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/8C.bin" 17A0C9h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/8D.bin" 17BA04h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/8E.bin" 17D3EEh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/8F.bin" 17EF95h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/90.bin" 1808ADh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/91.bin" 1822C7h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/92.bin" 18342Ch 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/93.bin" 184014h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/94.bin" 184E8Dh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/95.bin" 184E92h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/96.bin" 18672Eh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/97.bin" 1881F7h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/98.bin" 189CC3h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/99.bin" 18B6FDh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/9A.bin" 18CE2Bh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/9B.bin" 18E3DFh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/9C.bin" 18FD4Ch 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/9D.bin" 191666h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/9E.bin" 192EA3h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/9F.bin" 1947A5h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/A0.bin" 195EC4h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/A1.bin" 19799Ah 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/A2.bin" 1995CEh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/A3.bin" 1995D3h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/A4.bin" 1995D8h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/A5.bin" 1995DDh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/A6.bin" 19B1F0h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/A7.bin" 19CD9Bh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/A8.bin" 19E835h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/A9.bin" 1A0389h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/AA.bin" 1A1DDBh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/AB.bin" 1A395Ch 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/AC.bin" 1A54DCh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/AD.bin" 1A6DC5h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/AE.bin" 1A8011h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/AF.bin" 1A8016h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/B0.bin" 1A801Bh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/B1.bin" 1A8020h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/B2.bin" 1A9463h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/B3.bin" 1AA7D7h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/B4.bin" 1AC1C7h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/B5.bin" 1ADA4Ch 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/B6.bin" 1AF18Bh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/B7.bin" 1B0ECCh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/B8.bin" 1B1B6Dh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/B9.bin" 1B1B72h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/BA.bin" 1B3383h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/BB.bin" 1B4938h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/BC.bin" 1B5F7Fh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/BD.bin" 1B7558h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/BE.bin" 1B88D3h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/BF.bin" 1B99E7h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/C0.bin" 1BAB74h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/C1.bin" 1BBE1Dh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/C2.bin" 1BD207h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/C3.bin" 1BE4E2h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/C4.bin" 1BF601h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/C5.bin" 1C05E5h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/C6.bin" 1C16F5h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/C7.bin" 1C2D06h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/C8.bin" 1C3D9Ah 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/C9.bin" 1C4E7Ah 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/CA.bin" 1C60F5h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/CB.bin" 1C6E38h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/CC.bin" 1C8331h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/CD.bin" 1C9BC0h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/CE.bin" 1CB3C1h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/CF.bin" 1CC851h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/D0.bin" 1CDD2Bh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/D1.bin" 1CF08Eh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/D2.bin" 1D024Fh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/D3.bin" 1D14B1h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/D4.bin" 1D2B38h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/D5.bin" 1D3881h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/D6.bin" 1D4A16h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/D7.bin" 1D5DBDh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/D8.bin" 1D73D8h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/D9.bin" 1D860Ch 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/DA.bin" 1D948Fh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/DB.bin" 1DA5EDh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/DC.bin" 1DA9B5h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/DD.bin" 1DA9BAh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/DE.bin" 1DC09Ah 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/DF.bin" 1DD8AFh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/E0.bin" 1DF294h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/E1.bin" 1E098Fh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/E2.bin" 1E204Ah 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/E3.bin" 1E39C5h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/E4.bin" 1E52CFh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/E5.bin" 1E6BFCh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/E6.bin" 1E830Eh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/E7.bin" 1E9105h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/E8.bin" 1EA1BEh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/E9.bin" 1EAF74h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/EA.bin" 1EC8C0h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/EB.bin" 1EDF2Ch 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/EC.bin" 1EF4F4h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/ED.bin" 1F0979h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/EE.bin" 1F1B56h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/EF.bin" 1F2C83h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/F0.bin" 1F4506h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/F1.bin" 1F5C84h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/F2.bin" 1F721Dh 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/F3.bin" 1F8786h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/F4.bin" 1F9CD2h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/F5.bin" 1FB1F8h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/F6.bin" 1FC500h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/F7.bin" 1FD627h 1 0
".\tools\lc\decomp.exe" "./roms/Marvelous_JP.sfc" "./gfx/jp/F8.bin" 1FE99Ch 1 0
