".\tools\lc\recomp.exe" "./gfx/jp/00.bin" "./gfx/jp/lz/00.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/01.bin" "./gfx/jp/lz/01.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/02.bin" "./gfx/jp/lz/02.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/03.bin" "./gfx/jp/lz/03.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/04.bin" "./gfx/jp/lz/04.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/05.bin" "./gfx/jp/lz/05.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/06.bin" "./gfx/jp/lz/06.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/07.bin" "./gfx/jp/lz/07.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/08.bin" "./gfx/jp/lz/08.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/09.bin" "./gfx/jp/lz/09.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/0A.bin" "./gfx/jp/lz/0A.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/0B.bin" "./gfx/jp/lz/0B.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/0C.bin" "./gfx/jp/lz/0C.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/0D.bin" "./gfx/jp/lz/0D.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/0E.bin" "./gfx/jp/lz/0E.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/0F.bin" "./gfx/jp/lz/0F.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/10.bin" "./gfx/jp/lz/10.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/11.bin" "./gfx/jp/lz/11.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/12.bin" "./gfx/jp/lz/12.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/13.bin" "./gfx/jp/lz/13.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/14.bin" "./gfx/jp/lz/14.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/15.bin" "./gfx/jp/lz/15.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/16.bin" "./gfx/jp/lz/16.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/17.bin" "./gfx/jp/lz/17.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/18.bin" "./gfx/jp/lz/18.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/19.bin" "./gfx/jp/lz/19.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/1A.bin" "./gfx/jp/lz/1A.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/1B.bin" "./gfx/jp/lz/1B.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/1C.bin" "./gfx/jp/lz/1C.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/1D.bin" "./gfx/jp/lz/1D.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/1E.bin" "./gfx/jp/lz/1E.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/1F.bin" "./gfx/jp/lz/1F.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/20.bin" "./gfx/jp/lz/20.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/21.bin" "./gfx/jp/lz/21.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/22.bin" "./gfx/jp/lz/22.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/23.bin" "./gfx/jp/lz/23.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/24.bin" "./gfx/jp/lz/24.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/25.bin" "./gfx/jp/lz/25.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/26.bin" "./gfx/jp/lz/26.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/27.bin" "./gfx/jp/lz/27.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/28.bin" "./gfx/jp/lz/28.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/29.bin" "./gfx/jp/lz/29.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/2A.bin" "./gfx/jp/lz/2A.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/2B.bin" "./gfx/jp/lz/2B.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/2C.bin" "./gfx/jp/lz/2C.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/2D.bin" "./gfx/jp/lz/2D.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/2E.bin" "./gfx/jp/lz/2E.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/2F.bin" "./gfx/jp/lz/2F.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/30.bin" "./gfx/jp/lz/30.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/31.bin" "./gfx/jp/lz/31.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/32.bin" "./gfx/jp/lz/32.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/33.bin" "./gfx/jp/lz/33.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/34.bin" "./gfx/jp/lz/34.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/35.bin" "./gfx/jp/lz/35.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/36.bin" "./gfx/jp/lz/36.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/37.bin" "./gfx/jp/lz/37.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/38.bin" "./gfx/jp/lz/38.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/39.bin" "./gfx/jp/lz/39.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/3A.bin" "./gfx/jp/lz/3A.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/3B.bin" "./gfx/jp/lz/3B.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/3C.bin" "./gfx/jp/lz/3C.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/3D.bin" "./gfx/jp/lz/3D.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/3E.bin" "./gfx/jp/lz/3E.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/3F.bin" "./gfx/jp/lz/3F.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/40.bin" "./gfx/jp/lz/40.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/41.bin" "./gfx/jp/lz/41.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/42.bin" "./gfx/jp/lz/42.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/43.bin" "./gfx/jp/lz/43.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/44.bin" "./gfx/jp/lz/44.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/45.bin" "./gfx/jp/lz/45.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/46.bin" "./gfx/jp/lz/46.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/47.bin" "./gfx/jp/lz/47.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/48.bin" "./gfx/jp/lz/48.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/49.bin" "./gfx/jp/lz/49.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/4A.bin" "./gfx/jp/lz/4A.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/4B.bin" "./gfx/jp/lz/4B.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/4C.bin" "./gfx/jp/lz/4C.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/4D.bin" "./gfx/jp/lz/4D.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/4E.bin" "./gfx/jp/lz/4E.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/4F.bin" "./gfx/jp/lz/4F.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/50.bin" "./gfx/jp/lz/50.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/51.bin" "./gfx/jp/lz/51.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/52.bin" "./gfx/jp/lz/52.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/53.bin" "./gfx/jp/lz/53.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/54.bin" "./gfx/jp/lz/54.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/55.bin" "./gfx/jp/lz/55.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/56.bin" "./gfx/jp/lz/56.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/57.bin" "./gfx/jp/lz/57.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/58.bin" "./gfx/jp/lz/58.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/59.bin" "./gfx/jp/lz/59.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/5A.bin" "./gfx/jp/lz/5A.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/5B.bin" "./gfx/jp/lz/5B.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/5C.bin" "./gfx/jp/lz/5C.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/5D.bin" "./gfx/jp/lz/5D.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/5E.bin" "./gfx/jp/lz/5E.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/5F.bin" "./gfx/jp/lz/5F.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/60.bin" "./gfx/jp/lz/60.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/61.bin" "./gfx/jp/lz/61.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/62.bin" "./gfx/jp/lz/62.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/63.bin" "./gfx/jp/lz/63.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/64.bin" "./gfx/jp/lz/64.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/65.bin" "./gfx/jp/lz/65.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/66.bin" "./gfx/jp/lz/66.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/67.bin" "./gfx/jp/lz/67.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/68.bin" "./gfx/jp/lz/68.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/69.bin" "./gfx/jp/lz/69.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/6A.bin" "./gfx/jp/lz/6A.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/6B.bin" "./gfx/jp/lz/6B.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/6C.bin" "./gfx/jp/lz/6C.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/6D.bin" "./gfx/jp/lz/6D.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/6E.bin" "./gfx/jp/lz/6E.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/6F.bin" "./gfx/jp/lz/6F.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/70.bin" "./gfx/jp/lz/70.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/71.bin" "./gfx/jp/lz/71.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/72.bin" "./gfx/jp/lz/72.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/73.bin" "./gfx/jp/lz/73.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/74.bin" "./gfx/jp/lz/74.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/75.bin" "./gfx/jp/lz/75.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/76.bin" "./gfx/jp/lz/76.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/77.bin" "./gfx/jp/lz/77.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/78.bin" "./gfx/jp/lz/78.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/79.bin" "./gfx/jp/lz/79.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/7A.bin" "./gfx/jp/lz/7A.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/7B.bin" "./gfx/jp/lz/7B.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/7C.bin" "./gfx/jp/lz/7C.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/7D.bin" "./gfx/jp/lz/7D.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/7E.bin" "./gfx/jp/lz/7E.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/7F.bin" "./gfx/jp/lz/7F.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/80.bin" "./gfx/jp/lz/80.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/81.bin" "./gfx/jp/lz/81.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/82.bin" "./gfx/jp/lz/82.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/83.bin" "./gfx/jp/lz/83.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/84.bin" "./gfx/jp/lz/84.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/85.bin" "./gfx/jp/lz/85.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/86.bin" "./gfx/jp/lz/86.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/87.bin" "./gfx/jp/lz/87.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/88.bin" "./gfx/jp/lz/88.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/89.bin" "./gfx/jp/lz/89.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/8A.bin" "./gfx/jp/lz/8A.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/8B.bin" "./gfx/jp/lz/8B.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/8C.bin" "./gfx/jp/lz/8C.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/8D.bin" "./gfx/jp/lz/8D.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/8E.bin" "./gfx/jp/lz/8E.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/8F.bin" "./gfx/jp/lz/8F.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/90.bin" "./gfx/jp/lz/90.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/91.bin" "./gfx/jp/lz/91.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/92.bin" "./gfx/jp/lz/92.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/93.bin" "./gfx/jp/lz/93.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/94.bin" "./gfx/jp/lz/94.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/95.bin" "./gfx/jp/lz/95.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/96.bin" "./gfx/jp/lz/96.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/97.bin" "./gfx/jp/lz/97.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/98.bin" "./gfx/jp/lz/98.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/99.bin" "./gfx/jp/lz/99.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/9A.bin" "./gfx/jp/lz/9A.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/9B.bin" "./gfx/jp/lz/9B.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/9C.bin" "./gfx/jp/lz/9C.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/9D.bin" "./gfx/jp/lz/9D.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/9E.bin" "./gfx/jp/lz/9E.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/9F.bin" "./gfx/jp/lz/9F.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/A0.bin" "./gfx/jp/lz/A0.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/A1.bin" "./gfx/jp/lz/A1.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/A2.bin" "./gfx/jp/lz/A2.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/A3.bin" "./gfx/jp/lz/A3.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/A4.bin" "./gfx/jp/lz/A4.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/A5.bin" "./gfx/jp/lz/A5.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/A6.bin" "./gfx/jp/lz/A6.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/A7.bin" "./gfx/jp/lz/A7.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/A8.bin" "./gfx/jp/lz/A8.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/A9.bin" "./gfx/jp/lz/A9.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/AA.bin" "./gfx/jp/lz/AA.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/AB.bin" "./gfx/jp/lz/AB.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/AC.bin" "./gfx/jp/lz/AC.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/AD.bin" "./gfx/jp/lz/AD.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/AE.bin" "./gfx/jp/lz/AE.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/AF.bin" "./gfx/jp/lz/AF.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/B0.bin" "./gfx/jp/lz/B0.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/B1.bin" "./gfx/jp/lz/B1.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/B2.bin" "./gfx/jp/lz/B2.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/B3.bin" "./gfx/jp/lz/B3.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/B4.bin" "./gfx/jp/lz/B4.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/B5.bin" "./gfx/jp/lz/B5.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/B6.bin" "./gfx/jp/lz/B6.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/B7.bin" "./gfx/jp/lz/B7.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/B8.bin" "./gfx/jp/lz/B8.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/B9.bin" "./gfx/jp/lz/B9.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/BA.bin" "./gfx/jp/lz/BA.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/BB.bin" "./gfx/jp/lz/BB.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/BC.bin" "./gfx/jp/lz/BC.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/BD.bin" "./gfx/jp/lz/BD.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/BE.bin" "./gfx/jp/lz/BE.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/BF.bin" "./gfx/jp/lz/BF.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/C0.bin" "./gfx/jp/lz/C0.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/C1.bin" "./gfx/jp/lz/C1.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/C2.bin" "./gfx/jp/lz/C2.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/C3.bin" "./gfx/jp/lz/C3.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/C4.bin" "./gfx/jp/lz/C4.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/C5.bin" "./gfx/jp/lz/C5.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/C6.bin" "./gfx/jp/lz/C6.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/C7.bin" "./gfx/jp/lz/C7.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/C8.bin" "./gfx/jp/lz/C8.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/C9.bin" "./gfx/jp/lz/C9.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/CA.bin" "./gfx/jp/lz/CA.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/CB.bin" "./gfx/jp/lz/CB.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/CC.bin" "./gfx/jp/lz/CC.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/CD.bin" "./gfx/jp/lz/CD.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/CE.bin" "./gfx/jp/lz/CE.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/CF.bin" "./gfx/jp/lz/CF.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/D0.bin" "./gfx/jp/lz/D0.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/D1.bin" "./gfx/jp/lz/D1.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/D2.bin" "./gfx/jp/lz/D2.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/D3.bin" "./gfx/jp/lz/D3.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/D4.bin" "./gfx/jp/lz/D4.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/D5.bin" "./gfx/jp/lz/D5.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/D6.bin" "./gfx/jp/lz/D6.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/D7.bin" "./gfx/jp/lz/D7.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/D8.bin" "./gfx/jp/lz/D8.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/D9.bin" "./gfx/jp/lz/D9.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/DA.bin" "./gfx/jp/lz/DA.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/DB.bin" "./gfx/jp/lz/DB.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/DC.bin" "./gfx/jp/lz/DC.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/DD.bin" "./gfx/jp/lz/DD.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/DE.bin" "./gfx/jp/lz/DE.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/DF.bin" "./gfx/jp/lz/DF.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/E0.bin" "./gfx/jp/lz/E0.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/E1.bin" "./gfx/jp/lz/E1.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/E2.bin" "./gfx/jp/lz/E2.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/E3.bin" "./gfx/jp/lz/E3.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/E4.bin" "./gfx/jp/lz/E4.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/E5.bin" "./gfx/jp/lz/E5.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/E6.bin" "./gfx/jp/lz/E6.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/E7.bin" "./gfx/jp/lz/E7.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/E8.bin" "./gfx/jp/lz/E8.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/E9.bin" "./gfx/jp/lz/E9.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/EA.bin" "./gfx/jp/lz/EA.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/EB.bin" "./gfx/jp/lz/EB.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/EC.bin" "./gfx/jp/lz/EC.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/ED.bin" "./gfx/jp/lz/ED.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/EE.bin" "./gfx/jp/lz/EE.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/EF.bin" "./gfx/jp/lz/EF.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/F0.bin" "./gfx/jp/lz/F0.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/F1.bin" "./gfx/jp/lz/F1.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/F2.bin" "./gfx/jp/lz/F2.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/F3.bin" "./gfx/jp/lz/F3.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/F4.bin" "./gfx/jp/lz/F4.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/F5.bin" "./gfx/jp/lz/F5.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/F6.bin" "./gfx/jp/lz/F6.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/F7.bin" "./gfx/jp/lz/F7.bin.lz" 0 19 0
".\tools\lc\recomp.exe" "./gfx/jp/F8.bin" "./gfx/jp/lz/F8.bin.lz" 0 19 0
